### ISSUE TITLE
Creative+ Issue with Minecolonies

### ISSUE THREAD

**Issue by Raycoms** [Tschipp/Creative-Plus-1.11.2#1]
Hey there, I'm one of the main devs of minecolonies and I noticed that when we use Creative+ the builder isn't recognizing water as water and is unable to place it (It wants the water from the create tab you're adding).

**Comment by Tschipp** [comment]
Oh crap! Yeah, that's because I'm adding a new ItemBlock for Water and Lava, which is probably not the smartest thing to do... I made the mod a long time ago and I've not rewritten it until this point. Gonna look into it.

**Comment by Raycoms** [comment]
Thanks, great. For now we'll have to remove it from the server to avoid
this =)

2017-11-18 23:16 GMT+00:00 Tschipp <notifications@github.com>:

**Comment by Tschipp** [comment]
Hey, sorry for only fixing this now. I just didn't have the time. In any case, it's fixed (I hope!)
